import unittest

from neo.rawio.openephysbinaryrawio import OpenEphysBinaryRawIO
from neo.test.rawiotest.common_rawio_test import BaseTestRawIO


class TestOpenEphysBinaryRawIO(BaseTestRawIO, unittest.TestCase):
    rawioclass = OpenEphysBinaryRawIO
    entities_to_test = [
        'v0.5.3_two_neuropixels_stream',
        'v0.4.4.1_with_video_tracking',
        'v0.5.x_two_nodes',
    ]

    files_to_download = [
        "v0.5.3_two_neuropixels_stream/Record_Node_107/settings.xml",
        "v0.5.3_two_neuropixels_stream/Record_Node_107/experiment1/recording1/sync_messages.txt",
        "v0.5.3_two_neuropixels_stream/Record_Node_107/experiment1/recording1/structure.oebin",
        "v0.5.3_two_neuropixels_stream/Record_Node_107/experiment1/recording1/events/Neuropix-PXI-116.0/TTL_1/full_words.npy",
        "v0.5.3_two_neuropixels_stream/Record_Node_107/experiment1/recording1/events/Neuropix-PXI-116.0/TTL_1/channel_states.npy",
        "v0.5.3_two_neuropixels_stream/Record_Node_107/experiment1/recording1/events/Neuropix-PXI-116.0/TTL_1/timestamps.npy",
        "v0.5.3_two_neuropixels_stream/Record_Node_107/experiment1/recording1/events/Neuropix-PXI-116.0/TTL_1/channels.npy",
        "v0.5.3_two_neuropixels_stream/Record_Node_107/experiment1/recording1/continuous/Neuropix-PXI-116.1/continuous.dat",
        "v0.5.3_two_neuropixels_stream/Record_Node_107/experiment1/recording1/continuous/Neuropix-PXI-116.1/timestamps.npy",
        "v0.5.3_two_neuropixels_stream/Record_Node_107/experiment1/recording1/continuous/Neuropix-PXI-116.0/continuous.dat",
        "v0.5.3_two_neuropixels_stream/Record_Node_107/experiment1/recording1/continuous/Neuropix-PXI-116.0/timestamps.npy",

        "v0.4.4.1_with_video_tracking/settings.xml",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/sync_messages.txt",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/structure.oebin",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/spikes/Spike_Viewer-125_124.0/spike_group_1/spike_electrode_indices.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/spikes/Spike_Viewer-125_124.0/spike_group_1/spike_waveforms.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/spikes/Spike_Viewer-125_124.0/spike_group_1/spike_times.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/spikes/Spike_Viewer-125_124.0/spike_group_1/spike_clusters.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/events/Message_Center-904.0/TEXT_group_1/text.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/events/Message_Center-904.0/TEXT_group_1/timestamps.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/events/Message_Center-904.0/TEXT_group_1/channels.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/events/Sync_Port-129.0/TTL_1/full_words.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/events/Sync_Port-129.0/TTL_1/channel_states.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/events/Sync_Port-129.0/TTL_1/timestamps.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/events/Sync_Port-129.0/TTL_1/channels.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/events/Tracking_Port-127.0/BINARY_group_2/metadata.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/events/Tracking_Port-127.0/BINARY_group_2/timestamps.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/events/Tracking_Port-127.0/BINARY_group_2/data_array.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/events/Tracking_Port-127.0/BINARY_group_2/channels.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/events/Tracking_Port-127.0/BINARY_group_1/metadata.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/events/Tracking_Port-127.0/BINARY_group_1/timestamps.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/events/Tracking_Port-127.0/BINARY_group_1/data_array.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/events/Tracking_Port-127.0/BINARY_group_1/channels.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/events/Rhythm_FPGA-100.0/TTL_1/full_words.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/events/Rhythm_FPGA-100.0/TTL_1/channel_states.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/events/Rhythm_FPGA-100.0/TTL_1/timestamps.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/events/Rhythm_FPGA-100.0/TTL_1/channels.npy",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/continuous/Rhythm_FPGA-100.0/continuous.dat",
        "v0.4.4.1_with_video_tracking/experiment1/recording1/continuous/Rhythm_FPGA-100.0/timestamps.npy",

        "v0.5.x_two_nodes/RecordNode105/experiment1/recording1/sync_messages.txt",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording1/structure.oebin",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording1/events/Message_Center-904.0/TEXT_group_1/text.npy",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording1/events/Message_Center-904.0/TEXT_group_1/timestamps.npy",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording1/events/Message_Center-904.0/TEXT_group_1/channels.npy",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording1/continuous/File_Reader-100.0/synchronized_timestamps.npy",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording1/continuous/File_Reader-100.0/continuous.dat",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording1/continuous/File_Reader-100.0/timestamps.npy",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording3/sync_messages.txt",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording3/structure.oebin",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording3/events/Message_Center-904.0/TEXT_group_1/text.npy",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording3/events/Message_Center-904.0/TEXT_group_1/timestamps.npy",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording3/events/Message_Center-904.0/TEXT_group_1/channels.npy",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording3/continuous/File_Reader-100.0/synchronized_timestamps.npy",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording3/continuous/File_Reader-100.0/continuous.dat",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording3/continuous/File_Reader-100.0/timestamps.npy",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording2/sync_messages.txt",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording2/structure.oebin",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording2/events/Message_Center-904.0/TEXT_group_1/text.npy",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording2/events/Message_Center-904.0/TEXT_group_1/timestamps.npy",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording2/events/Message_Center-904.0/TEXT_group_1/channels.npy",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording2/continuous/File_Reader-100.0/synchronized_timestamps.npy",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording2/continuous/File_Reader-100.0/continuous.dat",
        "v0.5.x_two_nodes/RecordNode105/experiment1/recording2/continuous/File_Reader-100.0/timestamps.npy",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording1/sync_messages.txt",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording1/structure.oebin",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording1/events/Message_Center-904.0/TEXT_group_1/text.npy",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording1/events/Message_Center-904.0/TEXT_group_1/timestamps.npy",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording1/events/Message_Center-904.0/TEXT_group_1/channels.npy",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording1/continuous/File_Reader-100.0/synchronized_timestamps.npy",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording1/continuous/File_Reader-100.0/continuous.dat",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording1/continuous/File_Reader-100.0/timestamps.npy",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording3/sync_messages.txt",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording3/structure.oebin",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording3/events/Message_Center-904.0/TEXT_group_1/text.npy",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording3/events/Message_Center-904.0/TEXT_group_1/timestamps.npy",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording3/events/Message_Center-904.0/TEXT_group_1/channels.npy",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording3/continuous/File_Reader-100.0/synchronized_timestamps.npy",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording3/continuous/File_Reader-100.0/continuous.dat",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording3/continuous/File_Reader-100.0/timestamps.npy",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording2/sync_messages.txt",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording2/structure.oebin",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording2/events/Message_Center-904.0/TEXT_group_1/text.npy",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording2/events/Message_Center-904.0/TEXT_group_1/timestamps.npy",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording2/events/Message_Center-904.0/TEXT_group_1/channels.npy",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording2/continuous/File_Reader-100.0/synchronized_timestamps.npy",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording2/continuous/File_Reader-100.0/continuous.dat",
        "v0.5.x_two_nodes/RecordNode103/experiment1/recording2/continuous/File_Reader-100.0/timestamps.npy",
    ]


if __name__ == "__main__":
    unittest.main()
