version: 2

build:
  os: ubuntu-20.04
  tools:
    python: "3.8"

sphinx:
   configuration: doc/source/conf.py

python:
  install:
    - method: pip
      path: .
    - requirements: doc/requirements_docs.txt
