package:
  name: neo
  version: "0.3.3"

source:
  fn: neo-0.3.3.tar.gz
  url: https://pypi.python.org/packages/source/n/neo/neo-0.3.3.tar.gz
  md5: 98e7e8948158f4492fc94d9d44367c91
#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - neo = neo:main
    #
    # Would create an entry point called neo that calls neo.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools
    - numpy >=1.3.0
    - quantities >=0.9.0

  run:
    - python
    - numpy >=1.3.0
    - quantities >=0.9.0

test:
  # Python imports
  imports:
    - neo
    - neo.core
    - neo.io
    - neo.test
    - neo.test.iotest

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://neuralensemble.org/neo
  license: BSD License
  summary: 'Neo is a package for representing electrophysiology data in Python, together with support for reading a wide range of neurophysiology file formats'

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
